apiVersion: v1
kind: Service
metadata:
  name: pg-greeting-service
spec:
  selector:
    app: pg-greeting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
---
kind: Endpoints
apiVersion: v1
metadata:
  name: pg-greeting-service
subsets:
- addresses:
  - ip: 172.18.255.201
  ports:
  - port: 32712
    name: pg-greeting-service
---
