services:
  backend:
    build:
      context: backend
      target: dev-envs
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=example
    networks:
      - spring-postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  spring-postgres:
